// DecompileToC.java — Ghidra headless postScript: decompile every function in the
// imported program to C and concatenate it into one .c file.
//
// Used by apk-roundtrip.sh `sources` to produce best-effort C for native .so libs:
//   analyzeHeadless <proj> <name> -import libfoo.so \
//     -scriptPath <scriptsdir> -postScript DecompileToC.java <out.c> -deleteProject
//
// The output is a best-effort, human-readable reconstruction — approximate and NOT
// recompilable. The round-trippable native layer is reassemblable asm (ddisasm), not C.
import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.util.task.ConsoleTaskMonitor;
import java.io.PrintWriter;

public class DecompileToC extends GhidraScript {
    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            println("DecompileToC: missing output path argument");
            return;
        }
        String outPath = args[0];

        DecompInterface di = new DecompInterface();
        di.openProgram(currentProgram);

        ConsoleTaskMonitor monitor = new ConsoleTaskMonitor();
        PrintWriter out = new PrintWriter(outPath, "UTF-8");
        try {
            out.println("// Best-effort C decompilation of " + currentProgram.getName());
            out.println("// Generated by Ghidra headless decompiler — APPROXIMATE, not recompilable.");
            out.println("// The round-trippable native layer is reassemblable asm, not this C.");
            out.println();

            int n = 0, failed = 0;
            for (Function f : currentProgram.getFunctionManager().getFunctions(true)) {
                if (monitor.isCancelled()) break;
                DecompileResults res = di.decompileFunction(f, 60, monitor);
                if (res != null && res.decompileCompleted()) {
                    out.println(res.getDecompiledFunction().getC());
                    out.println();
                    n++;
                } else {
                    out.println("// [decompilation failed] " + f.getName()
                            + " @ " + f.getEntryPoint());
                    out.println();
                    failed++;
                }
            }
            println("DecompileToC: wrote " + n + " functions (" + failed
                    + " failed) to " + outPath);
        } finally {
            out.close();
            di.dispose();
        }
    }
}
